accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import SignUpView, SubmittableLogoutView, UserProfileView

app_name = "accounts"

urlpatterns = [
    path("", UserProfileView.as_view(), name="user_profile"),
    path("sign_up/", SignUpView.as_view(), name="sign_up"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("logout/request/", SubmittableLogoutView.as_view(), name="logout_request"),
]

finalProject/urls.py
from django.contrib import admin
from django.urls import include, path

from scheduler.views import IndexView, LoginUserView, exercise

urlpatterns = [
    path("admin/", admin.site.urls),
    path("scheduler/", include("scheduler.urls", namespace="scheduler")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", IndexView.as_view(), name="index"),
    path("user/login", LoginUserView.as_view(), name="user_login"),
    path("<str:exercise_type>/", exercise, name="exercise"),
]

scheduler/urls.py
from django.urls import path

from scheduler.views import HallSelection, SchedulerView, cancel_registration, register

app_name = "scheduler"

urlpatterns = [
    path("", HallSelection.as_view(), name="hall_selection"),
    path("<str:room_type>/", SchedulerView.as_view(), name="table"),
    path(
        "<str:room_type>/register/<slug:requested_date>/<str:requested_time>/",
        register,
        name="register",
    ),
    path(
        "<str:room_type>/register/<slug:requested_date>/<str:requested_time>/cancel/",
        cancel_registration,
        name="cancel",
    ),
]

templates/base.html
{% load static %}

<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}"{% endif %}>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Quadzzila Gym</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <!--link rel="stylesheet" href="//cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css"-->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.2/css/jquery.dataTables.css">
    <link rel="stylesheet" href="{% static 'static_css/animate.css' %}"/>
    <link rel="stylesheet" href="{% static 'static_css/schedule.css' %}">
    <link rel="icon" href="data:;base64,iVBORw0KGgo=">

    <!-- JavaScript -->
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.2/js/jquery.dataTables.js"></script>
    <!--script src="//cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script-->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
            integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"
            integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/"
            crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/1db2ef141e.js" crossorigin="anonymous"></script>
    <script src="{% static 'static_js/wow.min.js' %}"></script>
    <script>new WOW().init();</script>
    <script src="{% static 'static_js/schedule.js' %}"></script>


</head>

<body style="position: relative; background-color: #141b25">
<nav class="navbar navbar-expand-lg navbar-dark fixed_top" style="background-color: darkslategrey; margin-bottom: 30px">
    <div class="container">
        <div class="hstack gap-3">
            <a class="navbar-brand"><img src="{% static 'static_img/ceratosaurus.png' %}" alt="logo" width="50"
                                         height="50"
                                         class="d-inline-block align-top"></a>
            <p class="lead" style="color: #6bc499; margin-top: 0; margin-bottom: 0">Quadzzila Gym</p>
        </div>
        <div class="navbar-nav ml-auto">
            <button class="navbar-toggler" type="button" data-bs-target="#navID" data-bs-toggle="collapse"
                    aria-controls="navID" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navID" style="margin-right: 10px">
                <div class="navbar_nav">
                    <a class="nav-item nav-link active btn-lg" href="{% url 'index' %}">
                        <i class="fas fa-home" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Home"
                           style="color: #6bc499"></i>
                    </a>
                </div>
            </div>
            {% if user.is_authenticated %}
                <div class="collapse navbar-collapse" id="navID" style="margin-right: 10px">
                    <div class="navbar-nav">
                        <a class="nav-item nav-link active" href="{% url 'scheduler:hall_selection' %}"><p class="lead"
                                                                                                           style="color: #6bc499; margin-top: 0; margin-bottom: 0">
                            Schedule</p></a>
                    </div>
                </div>
                <div class="collapse navbar-collapse" id="navID" style="margin-right: 10px">
                    <div class="navbar-nav">
                        <a class="nav-item nav-link active" href="{% url 'accounts:user_profile' %}">
                            <p class="lead" style="color: #6bc499; margin-top: 0; margin-bottom: 0">User Profile:
                                <b style="color: #8fb8fe">{{ user.username }}</b></p>
                        </a>
                    </div>
                </div>
                <div class="collapse navbar-collapse" id="navID">
                    <div class="navbar-nav">
                        <a class="nav-item nav-link active"
                           href="{% url 'accounts:logout_request' %}">
                            <p class="lead" style="color: #6bc499; margin-top: 0; margin-bottom: 0">Log Out</p>
                        </a>
                    </div>
                </div>
            {% else %}
                <div class="collapse navbar-collapse" id="navID" style="margin-right: 10px">
                    <div class="navbar-nav">
                        <a class="nav-item nav-link active" href="{% url 'accounts:login' %}">
                            <p class="lead" style="color: #6bc499; margin-top: 0; margin-bottom: 0">Log In</p>
                        </a>
                    </div>
                </div>
                <div class="collapse navbar-collapse" id="navID">
                    <div class="navbar-nav">
                        <a class="nav-item nav-link active" href="{% url 'accounts:sign_up' %}">
                            <p class="lead" style="color: #6bc499; margin-top: 0; margin-bottom: 0">Sign Up</p>
                        </a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</nav>


<div class="jumbotron jumbotron-fluid" style="background-color: #141b25; width: 100%; height:inherit">
    <div class="container-fluid" style="width: 100%">
        <div class="row">
            <div class="col-8">
                {% block content %}{% endblock %}
            </div>
            <div class="col d-none d-md-block" style="padding-left: 0">
                <img src="{% static 'static_img/quadzilla.png' %}" alt="Quadzilla" class="img-fluid float-start my-5">
            </div>
        </div>
    </div>
</div>


<footer class="container-fluid"
        style="background-color: darkslategray; padding: 10px 10px; position: absolute; margin-top: 50px">
    <div class="hstack gap-3 justify-content-center" style="color: #141b25">
        <div>Icons made by <a style="color: #8fb8fe" href="https://www.freepik.com" title="Freepik">Freepik</a>
            from <a style="color: #8fb8fe" href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com </a>
        </div>
        <div class="vr"></div>
        <div>Image from <a style="color: #8fb8fe"
                           href="https://www.teeturtle.com/products/quadzilla?variant=31549143753">Teeturtle</a></div>
    </div>
    <hr style="color: #141b25">
    <div class="text-center" style="color: #141b25; font-size: medium">© 2021 <a href="https://gitlab.com/vixen_python"
                                                                                 title="vixen_python"
                                                                                 style="color: #8fb8fe">vixen_python</a>
    </div>
</footer>

</body>

</html>

templates/exercise.html
{% extends 'base.html' %}
{% load scheduler_tags %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1 class="display-3" style="color: #6bc499">{{ exercise.name }}</h1>
                <hr class="my-4" style="border-color: darkslategrey">
                <p class="lead" style="color: lightgray; line-height: 1.7">{{ exercise.description }}</p>
                <a href="{% url 'index' %}" class="btn" style="color: #6bc499"><i class="fas fa-arrow-alt-circle-left"
                                                                                  data-bs-toggle="tooltip" title="Back"
                                                                                  data-bs-placement="bottom"
                                                                                  style="background-color: #141b25; font-size: 4rem"></i></a>
            </div>
            <div class="col">
                <h1 class="display-3" style="color: #6bc499"> Classes </h1>
                <hr class="my-4" style="border-color: darkslategrey">
                {% for event in exercise.events.all %}
                    {% if event.active_schedules %}
                    <ul>
                        <li class="lead"
                            style="color: lightgray">
                            {{ event.difficulty_level|difficulty_enum|capfirst }}
                            with {{ event.lector.fullname }}:
                            {% for class in event.active_schedules %}
                                <ul>
                                    <li class="lead"
                                        style="color: lightgray; font-size: 0.8em">
                                        {{ class.day_of_week }} {{ class.time|time:"G:i" }}</li>
                                </ul>
                            {% endfor %}
                        </li>
                    </ul>
                    {% endif %}
                {% endfor %}
                {% if user.is_authenticated %}
                    <a href="{% url 'scheduler:table' exercise.events.first.schedule.first.gym_hall|hall_enum %}"
                       class="btn" style="color: #6bc499"><i class="far fa-calendar-alt"
                                                             data-bs-toggle="tooltip"
                                                             title="Look in the schedule"
                                                             data-bs-placement="bottom"
                                                             style="background-color: #141b25; font-size: 4rem"></i>
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/form.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <table style="color: lightgray" class="lead">
            {{ form }}
        </table>
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
{% endblock %}

templates/hall_selection.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid">
        <h2 class="display-3" style="color: #6bc499">Select Hall</h2>
        <hr class="my-4" style="border-color: darkslategrey">
        <div class="d-flex flex-row justify-content-start align-items-center wow slideInLeft" data-wow-duration="1s">
            <div><img src="{% static 'static_img/mirror_room.png' %}" alt="Mirror room"
                      class="rounded-circle float-start" style="height: 20rem"></div>
            <div><a class="btn" style="color: #6bc499"
                    href="{% url 'scheduler:table' 'mirror_room' %}"><h3 class="display-4 px-4" style="color: #6bc499">
                Mirror Room<i class="fas fa-angle-double-right" style="font-size: 3rem; padding-left: 20px"
                              data-bs-toggle="tooltip" title="Go to schedule"
                              data-bs-placement="right"></i></h3></a></div>

        </div>
        <div class="d-flex flex-row justify-content-end align-items-center wow slideInRight" data-wow-duration="1s"
             data-wow-delay="0.5s">
            <div><a class="btn" style="color: #6bc499"
                    href="{% url 'scheduler:table' 'inside_hall' %}"><h3 class="display-4 px-4" style="color: #6bc499">
                <i class="fas fa-angle-double-left"
                   style="font-size: 3rem; padding-right: 20px"
                   data-bs-toggle="tooltip" title="Go to schedule"
                   data-bs-placement="left"></i>Inside Hall</h3></a></div>
            <div><img src="{% static 'static_img/inside.png' %}" alt="Inside hall" class="rounded-circle float-end"
                      style="font-size: 20rem"></div>
        </div>
        <div class="d-flex flex-row justify-content-start align-items-center wow slideInLeft" data-wow-duration="1s"
             data-wow-delay="1s">
            <div>><img src="{% static 'static_img/outside.png' %}" alt="Outside" class="rounded-circle float-start"
                       style="height: 20rem"></div>
            <div><a class="btn " style="color: #6bc499" href="{% url 'scheduler:table' 'outside' %}"><h3
                    class="display-4 px-4" style="color: #6bc499">Outside<i
                    class="fas fa-angle-double-right" style="font-size: 3rem; padding-left: 20px"
                    data-bs-toggle="tooltip"
                    title="Go to schedule"
                    data-bs-placement="right"></i></h3></a></div>
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container mt-2" style="height: inherit">
        <h2 class="display-4" style="color: #6bc499">Welcome to the gym <b>QUADZZILA</b></h2>
        <div class="row" style="height: inherit">
            {% for exercise in object_list %}
                <div class="col-md-4 mt-5">
                    <div class="card text-center mb-3 h-100 border-0"
                         style="width: content-box; background-color: #8fb8fe">
                        <img src="{% static exercise.image_name %}" alt="{{ exercise.name }}" class="rounded-top">
                        <div class="card-body rounded-bottom" style="background-color: #405071">
                            <a href="{% url 'exercise' exercise.name %}" class="btn"
                               style="color: #8fb8fe; font-size: 3rem">
                                <h3 class="card-title" style="color: #8fb8fe">{{ exercise.name }}
                                <i class="fas fa-info-circle"
                                   data-bs-toggle="tooltip"
                                   title="Learn More"
                                   data-bs-placement="bottom" style="background-color: #405071"></i></h3></a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% load scheduler_tags %}

{% block content %}
    {% if schedule %}
        <div class="container">
            <div class="row">
                <div class="col">
                    <h2 class="display-3"
                        style="color: #6bc499">{{ schedule.date|date:"l j.n." }} {{ schedule.time|time:"G:i" }}</h2>
                    <h2 class="display-3" style="color: #6bc499; font-size: 2rem"> {{ schedule.event.exercise.name }} with <i style="color: #8fb8fe">{{ schedule.event.lector.first_name }}
                                {{ schedule.event.lector.last_name }}</i></h2>
                    <hr class="my-4" style="border-color: darkslategrey">
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <form method="POST">
                        {% csrf_token %}
                        <div style="color: lightgray; margin-bottom: 30px">
                            <h3 class="lead"> Gym hall: {{ schedule.gym_hall|hall_enum|capfirst }}</h3>


                            <h3 class="lead"> Price: {{ schedule.event.price }},-</h3>
                            <h3 class="lead"> Difficulty
                                level: {{ schedule.event.difficulty_level|difficulty_enum|capfirst }}</h3>
                            <h3 class="lead"> Duration: {{ schedule.event.duration }} h</h3>
                            <h3 class="lead">
                                Capacity: {{ schedule.capacity_filled }}/{{ schedule.event.capacity }}</h3>
                        </div>
                        {% if registered %}
                            <input type="submit" formaction="{{ cancel_url }}" value="Cancel" class="btn btn-danger">
                        {% else %}
                            {% if schedule.capacity_filled == schedule.event.capacity %}
                                <div class="alert" role="alert"
                                     style="background-color: #405071; border-color: #405071">
                                    <h3 class="display-5" style="color: lightgray"><i class="fas fa-sad-tear"
                                                                                      style="color: lightgray; margin-right: 10px"></i>You
                                        can not subscribe, the capacity of this class is full</h3></div>
                            {% else %}
                                <input type="submit" value="Submit" class="btn btn-primary">
                            {% endif %}
                        {% endif %}
                    </form>
                </div>
                <div class="col">
                <h3 class="lead" style="color: lightgray">Participants:</h3>
                <div class="row">
                    {% for participation in schedule.participations.all %}
                        <div class="col-4 lead" style="color: #8fb8fe">{{ participation.participant.username }}</div>
                    {% endfor %}
                </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <a href="{% url 'scheduler:table' schedule.gym_hall|hall_enum %}" class="btn"
                       style="color: #6bc499"><i
                            class="fas fa-arrow-alt-circle-left"
                            data-bs-toggle="tooltip" title="Back"
                            data-bs-placement="bottom" style="background-color: #141b25; font-size: 4rem"></i></a>
                </div>
                <div class="col-9">
                    {% if messages %}
                        <div class="alert wow flipInX" role="alert"
                             style="color: #141b25; background-color: #6bc499; border-color: #6bc499; margin-bottom: 0">
                            {% for message in messages %}
                                <div class="lead" style="margin-bottom: 0; font-size: 2rem"><i
                                        class="fas fa-check-square"
                                        style="font-size: 2rem; padding-right: 2rem"></i>
                                    {{ message }}</div>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    {% else %}
        <h3> There is no class in this combination of date and time</h3>
    {% endif %}
{% endblock %}

templates/schedule.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <ul class="nav nav-tabs" style="border-color: #6bc499">
        <li class="nav-item">
            <a class="nav-link {% if room_type == 'mirror_room' %} active {% endif %} lead"
               href="{% url 'scheduler:table' 'mirror_room' %}">Mirror Room</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if room_type == 'inside_hall' %} active {% endif %} lead"
               href="{% url 'scheduler:table' 'inside_hall' %}">Inside Hall</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if room_type == 'outside' %} active {% endif %} lead"
               href="{% url 'scheduler:table' 'outside' %}">Outside</a>
        </li>
    </ul>


    <div class="container-fluid" style="width: 100%; padding-left: 0; padding-right: 0">
        <table id="id-tab-schedule" class="display cell-border compact" style="width:100%">
            {# days of week #}
            <thead style="background-color: #141b25; border-color: #141b25">
            <tr>
                <th style="border-color: #141b25"></th>
                {% for row in header %}
                    <th class="lead" style="color: white; font-weight: normal">{{ row.name }}</th>
                {% endfor %}
            </tr>
            </thead>
            {# hours of day #}
            <tbody>
            {% for hour in rows %}
                <tr>
                    <th class="lead"
                        style="background-color: #141b25; color: white; border-color: #141b25; width: 20px">{{ hour.hour }}</th>
                    {% for item in hour.days %}
                        {% if item.event %}
                            <td id="schedule-cell"  {% if item.participate %}
                                style="background-image: radial-gradient(rgba(47,79,79,0.7), rgba(47,79,79,1), #141b25); border-color: #141b25; cursor: pointer; color: white" {% else %}
                                style="background-image: radial-gradient(rgba(107,196,153,0.4), rgba(107,196,153,1)); border-color: #141b25; cursor: pointer; color: #405071" {% endif %}
                                data-link="{% url 'scheduler:register' room_type item.date hour.hour %}">
                                <p class="small" style="margin-bottom: 0; text-align: center">
                                    <b>{{ item.event.exercise.name }}</b>
                                    <br>
                                    {{ item.event.lector.fullname }}
                                    <br>
                                    {{ item.schedule.capacity_filled }}/{{ item.event.capacity }}
                                </p>
                            </td>
                        {% else %}
                            <td style="background-image:radial-gradient(rgba(64,80,113,0.7), rgba(64,80,113,0.8), rgba(64,80,113,1)) ; width: 120px; height: 60px; border-color: #141b25"></td>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

templates/user_card.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1 class="display-3" style="color: #8fb8fe">{{ user.username }}</h1>
                <hr class="my-4" style="border-color: darkslategrey">
                <ul class="lead" style="color: lightgray">
                    <li><b>First name: </b>{{ user.first_name|capfirst }}</li>
                    <li><b>Last name: </b>{{ user.last_name|capfirst }}</li>
                    <li><b>Email: </b>{{ user.profile.email }}</li>
                    <li><b>Phone number: </b>{{ user.profile.phone_number }}</li>
                    <li><b>Date of Birth: </b>{{ user.profile.date_of_birth|date:"j. F Y" }}</li>
                </ul>
            </div>
            <div class="col">
                <h1 class="display-3" style="color: #6bc499">Your classes</h1>
                <hr class="my-4" style="border-color: darkslategrey">
                <ul class="lead">
                    {% for class in user.active_registrations %}
                        <li style="color: lightgray">
                            <form action="{{ class.cancel_url }}" method="POST">
                                {{ class.schedule_event.date|date:"l j.n." }} {{ class.schedule_event.time|time:"G:i" }} {{ class.schedule_event.event.exercise.name }}
                                {% csrf_token %}
                                <button type="submit" class="btn" style="color: red"><i
                                        class="far fa-window-close" data-bs-toggle="tooltip" title="Cancel"
                                        data-bs-placement="right"
                                        style="background-color: #141b25; font-size: 2rem"></i>
                                </button>
                            </form>
                        </li>
                    {% endfor %}
                </ul>

            </div>
        </div>
    </div>
{% endblock %}